
server:
  port: 8888
spring:
  application:
    name: bcp-bootcamp-configserver

  cloud:
    config:
      server:
        git:
          uri: https://github.com/crlp/bcp-bootcamp-repoconfig.git
          default-label: main
          timeout: 10
